# Generated by Django 5.2 on 2025-05-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Descripción',
            new_name='descripcion',
        ),
    ]
